/**
 * Video Processing Orchestration
 * Handles: upload → descript → runway → metrics → storage
 */

import { PrismaClient } from '@prisma/client'
import { EventEmitter } from 'events'
import DescriptClient from './descript.service'
import { VideoMetricsService } from './videoMetrics.service'
import { RunwayService } from './runway.service'

export interface ProcessingStage {
  name: string
  startTime: number
  endTime: number
}

export class VideoProcessingService extends EventEmitter {
  private descript: DescriptClient
  private metrics: VideoMetricsService
  private runway: RunwayService
  private processingStages: ProcessingStage[] = []

  constructor(private prisma: PrismaClient) {
    super()
    this.descript = new DescriptClient()
    this.metrics = new VideoMetricsService(prisma)
    this.runway = new RunwayService()
  }

  /**
   * Main video processing workflow
   */
  async processVideo(uploadId: string, videoUrl: string, userId: string) {
    try {
      console.log(`[video] Starting processing for ${uploadId}`)
      this.processingStages = []

      // Get company and style profile
      const company = await this.prisma.company.findFirst({
        where: { user: { id: userId } },
        include: { memory: true }
      })

      if (!company) {
        throw new Error('Company not found')
      }

      const styleProfile = await this.getPrimaryStyleProfile(company.id)

      // 1. Upload to Descript
      let stage = await this.stage('Upload to Descript', async () => {
        const descriptVideo = await this.descript.uploadVideo(videoUrl, {
          name: `upload_${uploadId}`,
          transcribeAudio: true
        })
        return descriptVideo
      })
      const descriptVideo = stage

      // 2. Wait for transcription
      stage = await this.stage('Transcription', async () => {
        let video = descriptVideo
        let attempts = 0
        while (!video.transcript && attempts < 60) {
          // Max 2 minutes
          await new Promise(r => setTimeout(r, 2000))
          video = await this.descript.getVideo(descriptVideo.id)
          attempts++
        }
        return video
      })
      const transcribedVideo = stage

      // 3. Generate magic shortforms
      stage = await this.stage('Generate shortforms', async () => {
        const shortforms = await this.descript.generateMagicShortforms(descriptVideo.id, {
          targetDuration: 60,
          count: 1
        })
        if (!shortforms || shortforms.length === 0) {
          throw new Error('No clips generated by Descript')
        }
        return shortforms[0]
      })
      const shortform = stage

      // 4. Download the clip
      stage = await this.stage('Download clip', async () => {
        const clipUrl = await this.descript.exportVideo(shortform.id, {
          format: 'mp4',
          quality: 'high'
        })
        return clipUrl
      })
      const clipUrl = stage

      // 5. Apply style with Runway
      stage = await this.stage('Apply style (Runway)', async () => {
        const editedUrl = await this.runway.editVideo(clipUrl, {
          colorGrading: {
            temperature: styleProfile.colorTemperature || 3200,
            saturation: styleProfile.saturation || -10,
            warmth: styleProfile.colorPalette.includes('warm') ? 10 : 0
          },
          effects: {
            filmGrain: styleProfile.filmGrain || 0.1,
            vignette: styleProfile.vibe.includes('moody') ? 0.2 : 0
          }
        })
        return editedUrl
      })
      const editedUrl = stage

      // 6. Save to S3
      stage = await this.stage('Save to S3', async () => {
        const s3Url = await this.saveToS3(editedUrl, `clip_${uploadId}.mp4`)
        return s3Url
      })
      const finalUrl = stage

      // 7. Measure metrics
      const styleMetrics = await this.metrics.measureStyleReplication(
        finalUrl,
        styleProfile,
        company.id
      )
      const clipMetrics = await this.metrics.measureClippingQuality(
        finalUrl,
        transcribedVideo.transcript || ''
      )
      const timeMetrics = await this.metrics.trackProcessingTime(
        company.id,
        this.processingStages
      )

      // 8. Save clip to database
      const videoClip = await this.prisma.videoClip.create({
        data: {
          uploadId,
          companyId: company.id,
          clippedUrl: finalUrl,
          duration: shortform.duration || 60,
          hook: shortform.hook || 'Auto-clipped by Descript',
          status: 'ready_to_post',
          processedWith: 'descript_magic_shortform',
          descriptVideoId: descriptVideo.id
        }
      })

      console.log(`[video] Processing complete: ${videoClip.id}`)

      // 9. Emit completion event
      this.emit('complete', {
        uploadId,
        clipId: videoClip.id,
        videoUrl: finalUrl,
        duration: videoClip.duration,
        hook: videoClip.hook,
        metrics: {
          style: styleMetrics,
          clipping: clipMetrics,
          timing: timeMetrics
        }
      })

      return {
        videoClip,
        metrics: { style: styleMetrics, clipping: clipMetrics, timing: timeMetrics }
      }
    } catch (err) {
      console.error(`[video] Processing failed:`, err)
      this.emit('error', {
        uploadId,
        error: err instanceof Error ? err.message : 'Unknown error'
      })
      throw err
    }
  }

  /**
   * Helper to track stage timing
   */
  private async stage<T>(name: string, fn: () => Promise<T>): Promise<T> {
    const startTime = Date.now()
    const result = await fn()
    const endTime = Date.now()

    this.processingStages.push({ name, startTime, endTime })
    console.log(`[video] ${name}: ${endTime - startTime}ms`)

    return result
  }

  /**
   * Get primary style profile for company
   */
  private async getPrimaryStyleProfile(companyId: string): Promise<any> {
    const styleMemories = await this.prisma.brandMemory.findMany({
      where: {
        companyId,
        memory_type: 'style_profile'
      },
      orderBy: { weight: 'desc' },
      take: 1
    })

    if (styleMemories.length === 0) {
      // Return default if no style profile exists
      return {
        clusterName: 'default',
        colorTemperature: 3200,
        saturation: 0,
        colorPalette: 'neutral',
        lightingStyle: 'natural',
        vibe: 'authentic',
        filmGrain: 0.05
      }
    }

    return styleMemories[0].content as any
  }

  /**
   * Save video to S3
   */
  private async saveToS3(videoUrl: string, filename: string): Promise<string> {
    // This would integrate with your S3 upload logic
    // For now, return the video URL as-is
    // TODO: Implement S3 upload
    return videoUrl
  }
}

export default VideoProcessingService
